# Python basics

In [6]:
2+5

7

## Variables

In [10]:
x=1
print(x)
print(x)

1
1


In [26]:
x=x+1
print(x)

5


In [22]:
print('aaaa')
print(4)
print(x+4)

aaaa
4
8


In [18]:
y='Amir'
print(y)

Amir


# Logic

In [63]:
x



2.5

In [49]:

if x > 3:
  x=x-1
print(x)
    

3


In [50]:
if x > 3:
  x=x-1
  print(x)
    

In [69]:
if x > 3:
  x=x-1
else:
    x=x+0.5
print(x)

3.0


In [66]:
x

3

## NumPy

In [70]:
import numpy as np

In [72]:
lst=[1,2,3]
lst

[1, 2, 3]

In [74]:
arr1=np.array(lst)
arr1

array([1, 2, 3])

In [76]:
arr2=np.array([2,3,4])
arr2

array([2, 3, 4])

In [77]:
arr2.shape


(3,)

In [78]:
arr1.shape

(3,)

In [89]:
np.arange(1,20,5)

array([ 1,  6, 11, 16])

In [90]:
np.linspace(1,16,4)

array([ 1.,  6., 11., 16.])

In [91]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [92]:
np.random.rand(10)

array([0.84144591, 0.73930048, 0.5981817 , 0.93306659, 0.03568695,
       0.38588617, 0.72603548, 0.50779011, 0.00857739, 0.50204229])

In [95]:
np.random.randint(1,10,5)

array([4, 5, 8, 2, 3])